version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "prodappstackserviceTaskDef3574354D:2"
        LoadBalancerInfo:
          ContainerName: "my-app"
          ContainerPort: 8081